### ISSUE TITLE
Some address types are not supported and lead to cities not being found

### ISSUE THREAD

**Issue by reynaldichernando** [borisghidaglia/meet-hn#9] opened 2024-09-17 18:35 UTC
I'm creating a separate issue to discuss the cities with diacritics not loading properly as shared in https://github.com/borisghidaglia/meet-hn/issues/6#issuecomment-2356415988.

I did try with the following location `Kaupō, United States` and it showed `City not found`.
<img width="497" alt="image" src="https://github.com/user-attachments/assets/5df8e264-8295-4a3a-8378-b1ad81ea1de9">

However, checking the OSM API call, it seems that the location was found, but it was just failing to do split on `cityName`.
<img width="1013" alt="image" src="https://github.com/user-attachments/assets/f3238ed0-5d8b-4022-a2d1-ade23a5adeba">
<img width="607" alt="image" src="https://github.com/user-attachments/assets/ebd8c8d4-f0cf-44bb-bf39-cce255eb52fc">

**Comment by reynaldichernando** [comment] 2024-09-17 18:39
I think the issue is right here when trying to construct the `cityName`, the value is undefined, because there is no field in the `address` object that is called "city", "town", "village", "province" or "municipality".

<img width="626" alt="image" src="https://github.com/user-attachments/assets/d2fe9dcf-6199-4fbd-b7e9-cd82a3de2a89">

At least for the sample location I picked above, the field is "hamlet" (See above)

**Comment by reynaldichernando** [comment] 2024-09-17 18:42
Ideally we don't have to guess what kind of field there is in the `address`, and just use this `name` field for the `cityName`.
![image](https://github.com/user-attachments/assets/b981fb2f-e5b5-4b01-a9a2-64cf6807c30e)

**Comment by reynaldichernando** [comment] 2024-09-17 18:48
Although it is also possible to find the name in the `address`, but we could determine the field name by checking the `addresstype`, for example the above `addresstype` is `hamlet`, which is also the field name used in the `address` object.

But not sure why we wanna do this (?)

Also fun fact, I found this the OSM API docs, it shows all the possible field that can appear in `address`.
https://nominatim.org/release-docs/latest/api/Output/#addressdetails

**Comment by borisghidaglia** [comment] 2024-09-18 10:35
Thanks for this investigation! 

> Ideally we don't have to guess what kind of field there is in the address, and just use this name field for the cityName.

I think you are right on this. 
The problem with cities needs a big change anyway. 
Indeed today users are unable to select a given city if its name exists several times in a country.
What I had in mind to fix this is to switch URLs from `/city/${countryCode}-${cityName}` to `/city/${lat}-${long}/${cityName}`. 
Today `${countryCode}-${cityName}` is the city id, but when this change occur it will be `${lat}-${long}`.
The nice thing with this is that `${cityName}` could be anything as it'll just be cosmetic in the URL. 

Also, I changed the title of the issue because the problem your pointing out is related to not being able to find cities with some address types that are not supported. Not cities with diacritics not being able to load properly.

Here is an example of the latter: [meet.hn/city/no-Tromsø](https://meet.hn/city/no-Tromsø)
And I think the problem is that here selectedCity is undefined. I didn't test the hypothesis though.

https://github.com/borisghidaglia/meet-hn/blob/d3d49d554453f94df4fb285eb469e2cd175d5791/app/(not-root)/city/%5Bid%5D/page.tsx#L27-L29

**Comment by borisghidaglia** [comment] 2024-10-08 19:35
Fixed with commit: https://github.com/borisghidaglia/meet-hn/commit/2ec73c8ae0bf47cdbbea54995e5d2e74ce10ccaf

Starting at this commit, meet.hn supports location search. Any location working on OpenStreetMap should work now.

**Closed as completed** 2024-10-08 19:35 UTC
